all:
	${MAKE} -C helloworld
	${MAKE} -C test_control
	${MAKE} -C simple_replay
	${MAKE} -C scs_replay


clean:
	${MAKE} -C helloworld clean
	${MAKE} -C test_control clean	
	${MAKE} -C simple_replay clean
	${MAKE} -C scs_replay clean
