CFLAGS=-Wall -g -O0 -pthread -I../../libVAPPControl
LDFLAGS=-L ../../libVAPPControl/ 

all: test_multi_thread

test_multi_thread: ../../libVAPPControl/libVAPPControl.a

clean:
	rm -f test_multi_thread
